name: Validate Airflow DAGs

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  DAG_validador:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Instalando Dependencias 
        run: |
          python -m pip install --upgrade pip
          pip install apache-airflow

      - name: Instalando Dependencias do Projeto
        run: |
          pip install -r requirements.txt

      - name: Inicializar o Airflow Database
        run: |
          airflow db init

      - name: Deploy das Variaveis do Airflow 
        run: |
          for json_file in variables/*.json; do
            airflow variables import "$json_file"
          done

      - name: Run Airflow DAG validation
        run: |
          find ./dags -name "*.py" -exec python {} \; -exec echo -n "Exit code: $?; " \; | grep -q "Exit code: 0;" || exit 1
